### ISSUE TITLE
Keycloak with OpenID

### ISSUE THREAD

**Issue by BeloborodovD** [xchwarze/oauthlogin-phpbb#1]
Could you please add a section on connecting to keycloak using the OpenID standard with fields to specify:
Issuer:
Redirect URI:

**Comment by xchwarze** [comment]
I have no idea what keycloak is. Would it be a free solution to Auth0?

**Comment by BeloborodovD** [comment]
> I have no idea what keycloak is. Would it be a free solution to Auth0?

I am looking for a solution that supports Keycloak, which supports protocols such as OpenID Connect, OAuth 2.0, and SAML.

Since my Keycloak is configured and connected to the active directory and takes the list of users from there.

PS. I may be confused, as I am just starting on this path.

**Comment by xchwarze** [comment]
The keycloak documentation is not really easy to understand. Anyway I don't plan to integrate more providers to this version.

If you need AD support you have to configure LDAP authentication: https://help.univention.com/t/cool-solution-setting-up-phpbb3-with-ldap-authentication/21825

**Comment by BeloborodovD** [comment]
Thanks for the answer. I'll search if I don't find anything I'll synchronize with AD. This was a backup option, since I wanted to make a single SSO authorization for a group of services where everything is tied to Keycloak.
